"""Auto-configure Asterisk for Simson.

When `asterisk.auto_configure` is enabled in the addon options, this module:
  1. Writes a minimal AMI user config so the addon can connect.
  2. Writes a dialplan context that Asterisk uses to ring PJSIP/SIP devices.
  3. Reloads only the relevant Asterisk modules (no full restart needed).

Users never need to touch asterisk conf files.
"""

from __future__ import annotations

import asyncio
import logging
import os
import subprocess
from pathlib import Path

logger = logging.getLogger("simson.asterisk_setup")

# Common Asterisk config root locations.
_ASTERISK_CONF_LOCATIONS = [
    Path("/etc/asterisk"),
    Path("/usr/local/etc/asterisk"),
]

# Generated file names inside the conf root.
_MANAGER_FILE = "manager.conf.d/simson.conf"   # included by manager.conf -> [include] manager.conf.d/*.conf
_DIALPLAN_FILE = "extensions.conf.d/simson.conf"  # included similarly


def _find_asterisk_root() -> Path | None:
    for p in _ASTERISK_CONF_LOCATIONS:
        if p.exists():
            return p
    return None


def _ensure_include(conf_file: Path, include_glob: str):
    """Ensure conf_file has a #include directive for include_glob.

    Some Asterisk distros don't have conf.d directories by default.
    We add the include at the bottom of the parent conf if not already there.
    """
    text = conf_file.read_text() if conf_file.exists() else ""
    include_line = f"#include {include_glob}"
    if include_line not in text:
        with open(conf_file, "a") as f:
            f.write(f"\n; Added by Simson addon\n{include_line}\n")
        logger.info("Added include directive to %s", conf_file)


def write_manager_conf(root: Path, ami_user: str, ami_secret: str) -> Path:
    """Write the Simson AMI user block."""
    conf_dir = root / "manager.conf.d"
    conf_dir.mkdir(exist_ok=True)
    dest = conf_dir / "simson.conf"

    content = f"""; Auto-generated by Simson addon — do not edit manually.
; To regenerate, restart the Simson addon with auto_configure enabled.

[{ami_user}]
secret = {ami_secret}
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
read = system,call,log,verbose,agent,originate,command
write = system,call,log,verbose,agent,originate,command
writetimeout = 5000
"""
    dest.write_text(content)
    logger.info("Wrote AMI user config: %s", dest)

    # Ensure manager.conf includes this directory.
    manager_main = root / "manager.conf"
    if manager_main.exists():
        _ensure_include(manager_main, "#include manager.conf.d/*.conf")
    return dest


def write_dialplan_conf(root: Path, context: str, ext_prefix: str) -> Path:
    """Write the Simson dialplan context."""
    conf_dir = root / "extensions.conf.d"
    conf_dir.mkdir(exist_ok=True)
    dest = conf_dir / "simson.conf"

    # Dial pattern: 9XXX → ring PJSIP/XXX (strip the prefix digit).
    # If no prefix configured, match any extension directly.
    if ext_prefix:
        pattern = f"_{ext_prefix}X."
        strip_prefix = f"${{EXTEN:{len(ext_prefix)}}}"
    else:
        pattern = "_X."
        strip_prefix = "${EXTEN}"

    content = f"""; Auto-generated by Simson addon — do not edit manually.

[{context}]
; Dial a PJSIP endpoint. Simson strips the prefix digit before dialling.
; e.g. originate extension 9101 → rings PJSIP/101
exten => {pattern},1,NoOp(Simson originated call to ${{EXTEN}})
 same => n,Dial(PJSIP/{strip_prefix},60,rT)
 same => n,Congestion(5)

; Fallback: try legacy chan_sip if PJSIP not available.
exten => {pattern},1,TrySystem(echo)
"""
    dest.write_text(content)
    logger.info("Wrote dialplan context: %s", dest)

    # Ensure extensions.conf includes this directory.
    ext_main = root / "extensions.conf"
    if ext_main.exists():
        _ensure_include(ext_main, "#include extensions.conf.d/*.conf")
    return dest


async def reload_asterisk_modules():
    """Signal Asterisk to reload manager and dialplan without restarting."""
    commands = [
        ["asterisk", "-rx", "manager reload"],
        ["asterisk", "-rx", "dialplan reload"],
    ]
    for cmd in commands:
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            out, err = await asyncio.wait_for(proc.communicate(), timeout=10)
            if proc.returncode == 0:
                logger.info("Asterisk reload OK: %s → %s", " ".join(cmd), out.decode().strip())
            else:
                logger.warning("Asterisk reload warning: %s → %s", " ".join(cmd), err.decode().strip())
        except asyncio.TimeoutError:
            logger.warning("Asterisk reload timed out: %s", " ".join(cmd))
        except FileNotFoundError:
            logger.warning("'asterisk' binary not found — is Asterisk installed? Skipping reload.")
            break
        except Exception as e:
            logger.warning("Asterisk reload error (%s): %s", " ".join(cmd), e)


async def setup_asterisk(ami_user: str, ami_secret: str, context: str, ext_prefix: str = "9") -> bool:
    """Full auto-configure flow.

    Writes conf files and reloads the relevant Asterisk modules.
    Returns True if files were written successfully (reload may still fail).
    """
    root = _find_asterisk_root()
    if not root:
        logger.error(
            "Asterisk config directory not found in %s. "
            "Install Asterisk or set the path manually.",
            [str(p) for p in _ASTERISK_CONF_LOCATIONS],
        )
        return False

    logger.info("Auto-configuring Asterisk at %s", root)
    try:
        write_manager_conf(root, ami_user, ami_secret)
        write_dialplan_conf(root, context, ext_prefix)
    except PermissionError as e:
        logger.error(
            "Cannot write Asterisk config (%s). "
            "Run the addon with sufficient permissions, or configure Asterisk manually.",
            e,
        )
        return False

    await reload_asterisk_modules()
    logger.info("Asterisk auto-configuration complete.")
    return True
